workflows:
  default-workflow:
    name: Flutter Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Ensure Android and iOS folders exist
        script: |
          if [ ! -d "android" ] || [ ! -d "ios" ]; then
            flutter create .
          fi
      - flutter clean
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
